### ISSUE TITLE
Got stuck when running test_minival_locally.sh and testing online

### ISSUE THREAD

**Issue by UltronAI** [StanfordVL/iGibsonChallenge2021#4]
I tried to run `test_minival_locally.sh --docker-name my_submission` but the procedure got stuck after "compiled per shaders" (in seemingly rendering the environments)

![image](https://user-images.githubusercontent.com/14848863/113425727-f8ce9400-9404-11eb-8e20-6ae7b14cd6b0.png)

However, this command worked well when I directly ran it in my local terminal.

`export CONFIG_FILE=~/eai/igibson-challenge-codes/iGibson/gibson2/examples/configs/locobot_social_nav.yaml; export TASK=social; export SPLIT=minival; export EPISODE_DIR=~/eai/igibson-challenge-codes/iGibson/gibson2/data/episodes_data/social_nav; CUDA_VISIBLE_DEVICES=5 python agent.py --agent-class SAC --ckpt-path ckpt`

This problem also seems to happen during online evaluation. It appeared to be "running" for a long time after I submitted the docker and finally (after 1 or 2 days), there are many "cancelled", 1 "finished" and even still 1 "running".

<img width="873" alt="image" src="https://user-images.githubusercontent.com/14848863/113426968-c9208b80-9406-11eb-9a03-3ae13b7494c5.png">

All of these results are of one submission.

**Comment by UltronAI** [comment]
My dockerfile is as follows:

```
FROM gibsonchallenge/gibson_challenge_2021:latest
ENV PATH /miniconda/envs/gibson/bin:$PATH

ADD agent.py /agent.py
ADD simple_agent.py /simple_agent.py
ADD rl_agent.py /rl_agent.py

ADD ckpt /ckpt

ADD mysubmission.sh /submission.sh
WORKDIR /
```

and mysubmission.sh is to run `python agent.py --agent-class SAC --ckpt-path ckpt`

BTW, if the process gets stuck online, how can I kill it forcibly?

**Comment by UltronAI** [comment]
I think I find something different between docker and local terminal is PyBullet. 

local terminal:

<img width="1191" alt="Xnip2021-04-03_13-18-49" src="https://user-images.githubusercontent.com/14848863/113469326-4c7dc380-947f-11eb-8ed3-dfbf268ff229.png">

In your installation guide, you say that your custom pybullet can speed up the physics in iGibson. Is it necessary for us to add it to the submission docker for faster evaluation?

**Comment by UltronAI** [comment]
Hi all. Could you let me know if you also have this problem?

**Comment by jangj8523** [comment]
Hi UltronAI, 

Thanks for raising this concern. There has been a slight overhaul to the backend so some of the submissions were cancelled and rerun multiple times. With regards the "Running" status, those statuses are simply posted to the EvalAI page and the submission is not running on our cluster. We will resolve this issue with EvalAi. We are sorry about the confusion. 

Your submission was made once but it was run multiple times (ie. submissions are cloned multiple times when it runs again) due to recent changes on our end. The submission with "Finished" status should contain the official results of your submission.  Thank you for raising this concern and for your participation!

**Comment by UltronAI** [comment]
Thanks for your reply and it works now!
